### ISSUE TITLE
Ubuntu 18: Missing JavaFX Dependencies

### ISSUE THREAD

**Issue by jjmilburn** [openconnectivity/otgc-linux#19]
Even after installing the dependencies as listed in the instructions from the `README`, running `/usr/bin/otgc.sh` results in the following error:

```
Error: Could not find or load main class org.openconnectivity.otgc.App
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by jjmilburn** [comment]
Note: This could be related to possibly conflicting install instructions - I have been following the guidance here:
https://github.com/openconnectivityfoundation/development-support/blob/master/otgc/README.md#install-otgc-on-linux-x86-debian

Which is from step 4 on the main 'iotivity.org/getting-started' page: https://iotivity.org/getting-started

**Comment by WAvdBeek** [comment]
removed the instructions in the other github.

please see the note after the curl script:

note: when the executable does start, please reinstall jfx manually by entering on the commandline:

sudo apt-get install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2

and start otgc on the command line: /usr/bin/otgc.sh



this should fix the issue.
note that these instructions are part of the script, but some how the automation does not work.

**Comment by jjmilburn** [comment]
Hi @WAvdBeek , thank you.

After running and installing the packages you mentioned, the error persists:

```
(base) j@XXX:~/Projects/otgc-try2/development-support/otgc/linux$ sudo apt-get install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenjfx-java is already the newest version (8u161-b12-1ubuntu2).
libopenjfx-jni is already the newest version (8u161-b12-1ubuntu2).
openjfx is already the newest version (8u161-b12-1ubuntu2).
The following package was automatically installed and is no longer required:
  openjfx-source
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
(base) j@XXX:~/Projects/otgc-try2/development-support/otgc/linux$ /usr/bin/otgc.sh 
Error: Could not find or load main class org.openconnectivity.otgc.App
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

This is on Ubuntu 18.04 LTS:

```
(base) j@XXX:~/Projects/otgc-try2/development-support/otgc/linux$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

I've tried reinstalling 'from scratch' as below:

```
sudo apt purge openjfx
curl https://openconnectivity.github.io/otgc-linux/setup.sh | bash
```

The above completes successfully, then I run:

```
(base) j@XXX:~/Projects/otgc-try2$ /usr/bin/otgc.sh 
Error: Could not find or load main class org.openconnectivity.otgc.App
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Then, I run:

```
(base) j@XXX:~/Projects/otgc-try2$ sudo apt-get install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2
Reading package lists... Done
Building dependency tree... 50%
Building dependency tree       
Reading state information... Done
libopenjfx-java is already the newest version (8u161-b12-1ubuntu2).
libopenjfx-java set to manually installed.
libopenjfx-jni is already the newest version (8u161-b12-1ubuntu2).
libopenjfx-jni set to manually installed.
openjfx is already the newest version (8u161-b12-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```

And, at this stage, OTGC still fails to start:

```
(base) j@XXX:~/Projects/otgc-try2$ /usr/bin/otgc.sh 
mkdir: cannot create directory ‘logs’: File exists
Error: Could not find or load main class org.openconnectivity.otgc.App
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by jjmilburn** [comment]
I was able to run the tool by modifying the `/usr/bin/otgc.sh` as follows:

```
#!/bin/bash                                                                     
                                                                                
export LD_LIBRARY_PATH=/usr/lib/otgc/lib/jni/:${LD_LIBRARY_PATH}                
                                                                                
                                                                                
cd /usr/share/otgc                                                              
mkdir logs                                                                      
                                                                                
DATE=$(date +"%Y%m%d%H%M")                                                      
                                                                                
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dprism.order=sw -jar /usr/lib/otgc/otgc-2.9.0-jfx.jar > logs/otgc_$DATE.log
```

I also have a newer version of Java installed on this machine, so it was necessary to tell the OTGC tool to launch using Java 8. The path for Java-8 is copied directly from the install script, so it should be the same hard-coded path for other users as well (?).

**Comment by jjmilburn** [comment]
It appears that the location which would need to change to fix this is located [here](https://github.com/openconnectivity/otgc-linux/blob/master/build/debian/otgc_native.sh#L120) 

Given that the path to the specific Java-8 version is already hardcoded as `JAVA_HOME` in [line 85 in the `otgc-cli` install script](https://github.com/openconnectivity/otgc-linux/blob/master/otgc-cli.sh#L85), a 'quick fix' would be to update `otgc_native.sh` to also hardcode the same path.

**Comment by simryang** [comment]
Can I know your working building environment?
OS? version? installed java version? additional environmental settings? or etc?
------------------
self answering...
ubuntu 16.04 openjdk 1.8.0_252 no other environmental setting..

**Comment by BenrenAi** [comment]
I got the same error:
/usr/bin/otgc.sh 
mkdir: cannot create directory ‘logs’: File exists
Error: Could not find or load main class org.openconnectivity.otgc.App
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

otgc-2.13.0

**Comment by BenrenAi** [comment]
otgc can run on my linux after use openjdk 1.8.0. I modified '/usr/bin/otgc.sh' as:
#!/bin/bash

export LD_LIBRARY_PATH=/usr/lib/otgc/lib/jni/:${LD_LIBRARY_PATH}

cd /usr/share/otgc
mkdir logs

DATE=$(date +"%Y%m%d%H%M")

/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dprism.order=sw -jar /usr/lib/otgc/otgc-2.13.0-jfx.jar > logs/otgc_$DATE.log

Thanks jjmilburn and simryang!

**Comment by DavidMarquezF** [comment]
Same problem with Ubuntu 20:

```
sudo apt-get install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '8u161-b12-1ubuntu2' for 'openjfx' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-java' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-jni' was not found
```

**Comment by juber-nunes** [comment]
Is there any solution or workaround for Ubuntu 20.04.

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

sudo apt-get install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '8u161-b12-1ubuntu2' for 'openjfx' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-java' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-jni' was not found


Following the setup.sh I get this

wModel.java:[98,13] cannot find symbol
[ERROR]   symbol:   class ListProperty
[ERROR]   location: class org.openconnectivity.otgc.viewmodel.ClientViewModel
[ERROR] /home/juber/iotivity/otgc/otgc-linux/src/main/java/org/openconnectivity/otgc/viewmodel/ClientViewModel.java:[100,12] cannot find symbol
[ERROR]   symbol:   class ListProperty
[ERROR]   location: class org.openconnectivity.otgc.viewmodel.ClientViewModel
[ERROR] /home/juber/iotivity/otgc/otgc-linux/src/main/java/org/openconnectivity/otgc/viewmodel/ClientViewModel.java:[104,19] cannot find symbol
[ERROR]   symbol:   class StringProperty
[ERROR]   location: class org.openconnectivity.otgc.viewmodel.ClientViewModel
[ERROR] /home/juber/iotivity/otgc/otgc-linux/src/main/java/org/openconnectivity/otgc/viewmodel/ClientViewModel.java:[106,18] cannot find symbol
[ERROR]   symbol:   class StringProperty
[ERROR]   location: class org.openconnectivity.otgc.viewmodel.ClientViewModel
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
+ cd ./build/debian
+ ./otgc_native.sh ../../target/jfx/app amd64
../../target/jfx/app/otgc-3.0.0-jfx.jar does not exist.
+ cd ..
+ cd ..
+ cd ..
+ sudo dpkg -r otgc
dpkg: warning: ignoring request to remove otgc which isn't installed
+ sudo dpkg -i ./otgc-linux/build/debian/out/otgc-3.0.0.deb
dpkg: error: cannot access archive './otgc-linux/build/debian/out/otgc-3.0.0.deb': No such file or directory
+ sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

**Comment by denisdonovan** [comment]
Regarding:  WAvdBeek commented on 23 Jan 2020 above .

I had this problem with the client installation:

I'm no expert but I believe the issue here is the repo for Ubuntu 20.04 does not have that specific version of opnjsk
             as per https://askubuntu.com/questions/1163534/installing-old-package-from-old-ubuntu-to-new-version-of-ubuntu
The solution is:
    1. Append deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe to /etc/apt/sources.list
    2. Do sudo apt update
    3. Run the curl script 
    4. Mark hold to prevent upgrade: apt-mark hold openjfx libopenjfx-jni libopenjfx-java
    5. To prevent any other complications Remove/comment out the entry from 1.
                     deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe from /etc/apt/sources.list
    6. Do sudo apt update
